security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                target: home_index  # Redirige vers la page d'accueil après déconnexion
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

        # Firewall spécifique pour la page "Ajouter une recette"
        secured_area:
            pattern: ^/recipe/new$
            security: true  # Assure-toi que l'accès est sécurisé
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
            # Vous pouvez ajouter d'autres règles si nécessaire

    # Contrôle d'accès
    access_control:
        # Accès à la zone admin uniquement pour les utilisateurs avec le rôle ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Accès à /profile uniquement pour les utilisateurs connectés (ROLE_USER)
        - { path: ^/user, roles: ROLE_USER }
        # Accès à la page "Ajouter une recette" uniquement pour les utilisateurs connectés
        - { path: ^/recipe/new, roles: ROLE_USER }
