twig:
  file_name_pattern: "*.twig"
  form_themes:
    - "bootstrap_5_layout.html.twig"  # Correction de l'orthographe
  default_path: "%kernel.project_dir%/templates"
  
when@test:
  twig:
    strict_variables: true
